# Generated by Django 2.0.7 on 2018-10-26 14:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('blog', '0003_auto_20181026_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Format',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='country',
            new_name='format',
        ),
    ]
