# Generated by Django 2.0.7 on 2018-10-26 14:25

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('blog', '0004_auto_20181026_1419'),
    ]

    operations = [
        
    ]
