# Generated by Django 2.0.7 on 2018-10-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181026_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='format',
            field=models.CharField(choices=[('1', 'mp3'), ('2', 'mp4'), ('3', 'mkv')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Format',
        ),
    ]
