# Generated by Django 2.0.7 on 2018-11-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181101_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
